### ISSUE TITLE
Use Navigator.OnLine when browser support this

### ISSUE THREAD

**Issue by rodrigocipriani** [chrisbolin/react-detect-offline#11]
To avoid too many requests only to verify if is online, when the browser support `Navigator.OnLine` use this, and if don´t, let work like is now.

Reference:
[https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine)

Ps.: If you like, I can work on it.

> Sorry my english, I´m Brazilian

**Comment by chrisbolin** [comment]
hey @rodrigocipriani! thanks for filing this. so unfortunately many browsers have only partial support for the `offline` and `online` events. we actually look for this support here: https://github.com/chrisbolin/react-detect-offline/blob/master/src/index.js#L9

**Comment by chrisbolin** [comment]
I'm going to close this for now, as we have the handling for supporting browsers. i also have a beta version that adds the ability for manual control. I'll get a link to that.

**Comment by chrisbolin** [comment]
check out `react-detect-offline@next` (`react-detect-offline@2.1.0`) for more control over polling...
more info here: https://github.com/chrisbolin/react-detect-offline/pull/10#issuecomment-377453040
