### ISSUE TITLE
Altering the state of external components

### ISSUE THREAD

**Issue by KBoohene** [chrisbolin/react-detect-offline#15]
Hi, I was wondering if any of your components returns some output(online or offline) that will allow me to change the state of another component?

Eg. Your component might return an "online" status, then maybe a callback function to allow me to alter the state of another component based on the "online" status.

If it's not existent could you please point me in the direction where I could get some help? I've been looking for how to do this with react js and I've hit a dead end.

**Comment by chrisbolin** [comment]
check out our `Detector` component: https://github.com/chrisbolin/react-detect-offline#advanced

This library, and most ReactJS libraries, use a top-down one-way data model. So you pass down information, but you don't pass "out" information. 

If you're just learn React i'd suggestion something like Thinking In React: https://reactjs.org/docs/thinking-in-react.html
