### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by newyork-anthonyng** [chrisbolin/react-detect-offline#2]
I think we can use Jest and Enzyme to get good test coverage for this library.

Let me know if you want me to create a Pull Request for this.

**Comment by chrisbolin** [comment]
Totally down for a PR!

**Comment by newyork-anthonyng** [comment]
Cool. I'll work on this later in the week when I have time.

**Comment by chrisbolin** [comment]
housekeeping and just close inactive issues. TOTALLY open to test PRs tho! :)
