### ISSUE TITLE
Feature Request: slow network detection

### ISSUE THREAD

**Issue by Aarbel** [chrisbolin/react-detect-offline#21]
HI @chrisbolin, thanks a lot for this component.

Did you thought about implementing slow network support ? Thanks a lot

# Why it's important
A user doesn't understand the behavior of an app under slow network connexion. Could be great to tell him his connexion is crap.

**Comment by chrisbolin** [comment]
probably out of scope for this lil project. sorry! :/ 

browsers are getting better and better support for things like this tho. check out https://developer.mozilla.org/en-US/docs/Web/API/Network_Information_API
