### ISSUE TITLE
Indication of  initial network status

### ISSUE THREAD

**Issue by leantide** [chrisbolin/react-detect-offline#25]
From what I can tell, I can get an onChange network status, but no ability to know the initial network status before the first change.

I understand the initial network status is available as the render prop of `<Detector>` but that status is only for the render. Within a React render, although I can use the state, I am not able to extract the state and use it outside the render like I can do for the onChange event.

Is there any way to get the initial network status?

**Comment by leantide** [comment]
Seems I can get this myself from window.navigator.onLine.

**Comment by chrisbolin** [comment]
For those interested in this problem, check out the example here: https://github.com/chrisbolin/react-detect-offline/issues/27#issuecomment-476976188

Also note that the `render` prop of `Detector` should be used far more often than `onChange`. If you are using `onChange` and not `render`, you're probably going to be mad at the library :D
