### ISSUE TITLE
Initial network status

### ISSUE THREAD

**Issue by brightpixels** [chrisbolin/react-detect-offline#27]
My question is related to a recent question that the original poster closed: https://github.com/chrisbolin/react-detect-offline/issues/25

I am using the Detector component, which works as expected, apart from arriving at the app with out a connection. 

My use case is that I want to be able to always display a warning modal, whenever the user goes offline, including if they arrive on app (i.e on app load) whilst offline (context: my react app is used as part of a Cordova/hybrid/webview app).

As mentioned, I am able to trigger the warning modal whenever the status of the connection changes to offline (using the onchancge and checking if status is offline). But I am unable to detect the initial connection status when the app first loads. I would appreciate any help/suggestion to get this working. 

Relevant code snippet

````
const [modalIsOpen, setModalIsOpen] = useState(false);
const closeModal = () => {
    setModalIsOpen(false);
};

  const handleConnectionChange = connectionStatus => {
    if (connectionStatus === false) {
      setModalIsOpen(true);
    }
  };
....
....
....
<Detector
            onChange={handleConnectionChange}
            render={() => (
              <ReactModal
                isOpen={modalIsOpen && isMobile}
                contentLabel="Offline"
                onRequestClose={closeModal}
              >
                <h1>You currently offline!</h1>
                <Button clickHandler={closeModal} type="button">OK</Button>
              </ReactModal>
            )}
          />

**Comment by chrisbolin** [comment]
thank you @brightpixels! I'll try to look at it tonight

**Comment by chrisbolin** [comment]
Thank you for the detailed write-up!

I think the solution here is just to re-think the hierarchy. Embrace React's one-way dataflow and have "react-detect-offline" be at a higher level than the modal. You don't even need `Detector`, just `Offline`:


```
import React, { useState } from "react";
import ReactDOM from "react-dom";
import ReactModal from "react-modal";
import { Offline } from "react-detect-offline";

function OfflineModal() {
  const [open, setOpen] = useState(true);
  return (
    <div className="App">
      <ReactModal isOpen={open}>
        You're offline!
        <br />
        <button onClick={() => setOpen(false)}>close</button>
      </ReactModal>
    </div>
  );
}

function App() {
  return (
    <div>
      Hello!
      <Offline>
        <OfflineModal />
      </Offline>
    </div>
  );
}
```

Try it out here:  https://codesandbox.io/s/9wxq2mx34

- The modal automatically opens whenever the user goes offline OR starts offline. 
- The modal can be closed by the user AND it automatically closes when the user goes online again.
- Even if the user closes the modal, going online and then offline _again_ will open it up, just like your code

**Comment by chrisbolin** [comment]
Let me know if that works for you!

**Comment by brightpixels** [comment]
Thanks! Will try this as soon (just away from laptop). However part of the requirement is to allow user to dismiss the modal even if they connect back online, which is why I was using the detector and checking for the type of status change.

**Comment by brightpixels** [comment]
Reporting back: What you explained here: https://github.com/chrisbolin/react-detect-offline/issues/27#issuecomment-476976188 works for me. However, is it possible that modal is explicitly dismissed by the user, even when the connection is regained.

**Comment by chrisbolin** [comment]
I'm not sure I quite understand this...
> However, is it possible that modal is explicitly dismissed by the user, even when the connection is regained.

If you're asking if the user still has to dismiss the modal when connection is regained, then no, they don't have to.

If you'd like to _force_ the user to dismiss the modal, you *can do this*, but you'll have to rewrite things. 

Could you list the steps you'd like the user to be able to take (or NOT be able to take)?

**Comment by brightpixels** [comment]
once a warning modal is shown to the user (telling the user they have lost connection), I would like to force the user to dismiss the modal. At the moment, modal can be dismissed by the user or it's automatically dismissed the moment the connection status become online.

Once user closes the modal, few seconds later they might get connection back and lose connection again which presents modal again, etc

**Comment by chrisbolin** [comment]
Still totally possible :) 

In that case you need to use the `render` method on `Detector`.

```jsx
import React, { useState } from "react";
import ReactModal from "react-modal";
import { Detector } from "react-detect-offline";

function OfflineModal({ online }) {
  const [open, setOpen] = useState(!online);
  const [prevOnline, setPrevOnline] = useState(null);

  if (online !== prevOnline) {
    // online status has changed
    setPrevOnline(online); 

    if (!online && !open) {
      // we're offline and the modal is closed
      setOpen(true);
    }  
  }


  return (
    <div className="App">
      <ReactModal isOpen={open}>
        Looks like you might be having connection issues.
        <br />
        <button onClick={() => setOpen(false)}>close</button>
      </ReactModal>
    </div>
  );
}

function App() {
  return (
    <Detector
      render={({ online }) => (
        <div>
          Hello! You're currently {online ? "online" : "offline"}.
          <OfflineModal online={online} />
        </div>
      )}
    />
  );
}
```

You can play with it here: https://codesandbox.io/s/kmxqmz587o

Note: this uses the "`getDerivedStateFromProps` via hooks" method here: https://reactjs.org/docs/hooks-faq.html#how-do-i-implement-getderivedstatefromprops. There might be a cleaner way to do things (see https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#anti-pattern-unconditionally-copying-props-to-state) but it's late :D

**Comment by brightpixels** [comment]
Thank you v much. I appreciate your time :)

**Comment by chrisbolin** [comment]
of course!
