### ISSUE TITLE
Remove/document the debug functionality

### ISSUE THREAD

**Issue by newyork-anthonyng** [chrisbolin/react-detect-offline#3]
Regarding the debug functionality [here](https://github.com/chrisbolin/react-detect-offline/blob/master/src/index.js#L46-L49).

I'm wondering if this functionality is helpful. I feel like most developers would instinctively go `offline ` from their Developer Tools.

**Comment by chrisbolin** [comment]
@newyork-anthonyng totally agree! the things you do when you don't think anyone with look at your code :D wanna send me a PR?

**Comment by chrisbolin** [comment]
@newyork-anthonyng thanks for reporting this! fixed in 1.0.6
