### ISSUE TITLE
switched from GET to HEAD

### ISSUE THREAD

**Issue by codejamninja** [chrisbolin/react-detect-offline#33]
Changed the method just broke all my code. Is there a reason for this?

![Screenshot from 2019-03-28 13-19-50](https://user-images.githubusercontent.com/6234038/55182722-4bad4b00-515c-11e9-87b8-6e984c05d20d.png)

**Comment by chrisbolin** [comment]
Oh no! That's not good. Could you be more specific about what "broke all my code" means?

**Comment by codejamninja** [comment]
It means that my code was using the GET method, and unexpectedly it started using the HEAD method.

**Comment by chrisbolin** [comment]
and the HEAD method does not work for your browser? Or is it endpoint
specific? Code to reproduce would be helpful!

**Comment by chrisbolin** [comment]
I’m sure I’m just missing something here. That change was from a community contributor, and it worked in my tests

**Comment by codejamninja** [comment]
Ah, no problem. People using this on the backend have already changed it to use `GET`, so probably you'll break things again if you revert back. Oh, well. Just keep me posted on what method you are using.

**Comment by chrisbolin** [comment]
> People using this on the backend

Ahh, that makes more sense. So what I think would be

**Comment by codejamninja** [comment]
Yeah, not a bad idea.

**Comment by chrisbolin** [comment]
```jsx
<Detector polling={{ method: "GET", ... }}/>
```

**Comment by chrisbolin** [comment]
and we'd default `method` to `"HEAD"`, as it's the lightest-weight

**Comment by chrisbolin** [comment]
here's the original rational for `HEAD`: https://github.com/chrisbolin/react-detect-offline/pull/20 (thanks to @alixaxel)

>>>This PR simply switches from GET to HEAD requests. For the purposes of this module, the actual server response is meaningless and therefore HEAD is better suited, not only does it generate a faster/lighter response, it also reduces the strain on the server.

**Comment by codejamninja** [comment]
Great, here is a pull request to fix it.

https://github.com/chrisbolin/react-detect-offline/pull/34

**Comment by chrisbolin** [comment]
closed issue, see PR #34
