### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by francisrod01** [chrisbolin/react-detect-offline#39]
Seems like the `Detector` bugs my Next.js server-side application on browser and system console.

```bash
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check your code at withData.js:125.
    in WithData(SignInPage) (at _document.js:9)
    in StyleSheetManager
    in Unknown
    in AppContainer
    in Container
    in App
TypeError: Cannot read property 'toLowerCase' of undefined
```

* I'm using `react@16.8.6`
* `react-detect-offline@2.3.0`
* `react-dom@16.8.6`
* `next@8.1.0`

**Comment by chrisbolin** [comment]
hmm, i'm not sure what that would be. `.toLowerCase` literally doesn't exist anywhere in this codebase: https://github.com/chrisbolin/react-detect-offline/blob/master/dist/index.js

i'm going to go ahead and close this, but feel free to open it if you investigate and see it really is an issue with `react-detect-offline`
