### ISSUE TITLE
desktop browsers unsupported

### ISSUE THREAD

**Issue by noformnocontent** [chrisbolin/react-detect-offline#4]
it dosnt work on desktop (firefox), if i just yank the cord

rather try to fetch base URL and see if 404 on load

**Comment by chrisbolin** [comment]
totally, i think we should have a 404 backup. i believe there is an issue on Chrome for Windows as well.

**Comment by chrisbolin** [comment]
For reference later: https://github.com/HubSpot/offline

**Comment by chrisbolin** [comment]
polling backup added in 1.0.6 for Windows Chrome. Windows Firefox added in 2.0.0

**Comment by chrisbolin** [comment]
hey @xfumihiro! if you can verify that linux firefox needs to be added to the unsupported browsers here
https://github.com/chrisbolin/react-detect-offline/blob/master/src/index.js#L7
just open a PR. thanks!
