### ISSUE TITLE
Don't listen to the online event if polling

### ISSUE THREAD

**Issue by tonyhallett** [chrisbolin/react-detect-offline#44]
This is my understanding

The purpose of polling is because the online event is not necessarily a true indicator of internet connection.  By listening to it when polling there can be a false positive until the next ping determines the true nature of the internet connection.

**Comment by chrisbolin** [comment]
I'm sorry, it is confusing. The polling is a _back up_. The only reason polling is there is to fill in the gaps of browser support. There's no fear of false positives; just a fear of missing support altogether :) 

Browsers are constantly adding and improving the online events, and those should be prioritized.

**Comment by tonyhallett** [comment]
I don't find it confusing. Both [mdn](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine) and [caniuse](https://caniuse.com/#feat=online-status) are clear that online does not always mean connection to the internet, after all that is why you are polling.

The clearest example I can provide is with firefox and work offline mode.  Disconnect from the internet and work offline with polling on. 

1. The code polls - state offline
2. Turn off work offline.  The online event is raised - **state online**
3.  The code polls - state offline - the true state.

If you do not listen to the online event when polling you will not get this false positive.
