### ISSUE TITLE
more control over polling 

### ISSUE THREAD

**Issue by barbalex** [chrisbolin/react-detect-offline#56]
I am building an offline-first app. It loads all data into the local store. On user-edits it edits the data in the local store an then tries to update the server. If react-detect-offline detects "offline", it waits for the app to be online again.

In other words: The app can do perfectly well without accessing the app server. All it needs to know is whether the api is accessible.

The app can also work without accessing the api. But it needs to know that the api is not accessible.

It would be much nicer if the app could specifically test whether this specific api is accessible rather than the internet generally. Some advantages:

- no problems if the generic url polled goes down
- no problems if the api goes down for a short while (maintenance etc.)

I found the `polling.url` option. The problem is this:

My api uses hasura. Hasura, being a graphql-api, accepts only post request. Hasura also has a `/healthz` endpoint that is built specifically for this task, responding to get-requests with helpful information or with a 500 status in case of errors (https://hasura.io/docs/1.0/graphql/manual/api-reference/health.html).

The problem is: react-detect-offline sends a head request. And this is not configurable (or I missed it). So all I can do is set the url of my web app or use the generic one included.

What do you think about being able to:

- choose the type of request sent (head, get, post)
- choose status codes that are accepted as healthy/online
- enforce polling

**Comment by barbalex** [comment]
I decided that this might be out of the scope of react-detect-offline.

Inspired by react-detect-offline I built a simple component that does what I want:
```jsx
import React, { useContext, useEffect } from 'react'
import { observer } from 'mobx-react-lite'
import axios from 'axios'

import { StoreContext } from '../models/reactUtils'

const config = {
  url: 'https://api.vermehrung.ch/healthz',
  timeout: 5000,
  interval: 5000,
}

const ping = async () => {
  let res
  try {
    res = await axios.get(config.url, { timeout: config.timeout })
  } catch (error) {
    // error can also be caused by timeout
    return false
  }
  if (res.status === 200) return true
  return false
}

const ApiDetector = () => {
  const store = useContext(StoreContext)
  const { online, setOnline } = store

  useEffect(() => {
    const pollingId = setInterval(() => {
      ping().then((nowOnline) => {
        if (online !== nowOnline) {
          setOnline(nowOnline)
        }
      })
    }, config.interval)
    return () => {
      clearInterval(pollingId)
    }
  }, [online, setOnline])

  return null
}

export default observer(ApiDetector)
```

Thanks for this great tool!

**Comment by chrisbolin** [comment]
@barbalex i'm glad you found this code to inspire you to build something on it!
